# -*- coding: utf-8 -*-
"""ite.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zC6Rw2lfinToLxqS_BVsGy4l3746KvtR
"""

#Can't run it here yet as ryu is not installed

"""
ite.py — Intelligent Traffic Engineering Controller
=====================================================
Project : Intelligent Traffic Engineering System (ITE)
Author  : SDN Lab
Stack   : Ryu (OpenFlow 1.3) + NumPy Q-Learning + Pandas logging

Architecture overview
─────────────────────
  ┌──────────────────────────────────────────────────────────┐
  │  Ryu App (ITE_Controller)                                │
  │                                                          │
  │   ① TrafficMonitor  ──► port stats every MONITOR_PERIOD │
  │          │                                               │
  │          ▼                                               │
  │   ② RewardCalculator ──► weighted score per switch-port  │
  │          │                                               │
  │          ▼                                               │
  │   ③ QLearningAgent  ──► Q-Table update  (NumPy array)   │
  │          │                                               │
  │          ▼                                               │
  │   ④ PacketIn handler ──► pick best action (next-hop)    │
  │          │                                               │
  │          ▼                                               │
  │   ⑤ FlowMod / PacketOut ──► push rule into OVS switch   │
  └──────────────────────────────────────────────────────────┘

Run inside your (sdn_project) virtual environment:
    ryu-manager ite.py --observe-links
"""

# ── Standard library ──────────────────────────────────────────────────────────
import os
import time
import random
import logging
from collections import defaultdict

# ── Third-party ───────────────────────────────────────────────────────────────
import numpy  as np
import pandas as pd

# ── Ryu framework ─────────────────────────────────────────────────────────────
from ryu.base                    import app_manager
from ryu.controller              import ofp_event
from ryu.controller.handler      import CONFIG_DISPATCHER, MAIN_DISPATCHER, set_ev_cls
from ryu.ofproto                 import ofproto_v1_3
from ryu.lib.packet              import packet, ethernet, ether_types
from ryu.lib                     import hub

# ─────────────────────────────────────────────────────────────────────────────
#  Global hyper-parameters  (tune these without changing any other code)
# ─────────────────────────────────────────────────────────────────────────────

# Q-Learning
ALPHA            = 0.1      # learning rate         (0 = never learn, 1 = forget past)
GAMMA            = 0.9      # discount factor       (how much future rewards matter)
EPSILON_START    = 1.0      # initial exploration   (100 % random at first)
EPSILON_MIN      = 0.05     # minimum exploration   (always keep 5 % curiosity)
EPSILON_DECAY    = 0.995    # per-episode decay     (slowly shift to exploitation)

# Network / topology
NUM_SWITCHES     = 5        # s1 … s5
MAX_PORTS        = 8        # maximum ports per switch in our topology
MONITOR_PERIOD   = 5        # seconds between stats polls
FLOW_IDLE_TIMEOUT = 10      # OVS idle timeout (s) — force re-decision
FLOW_HARD_TIMEOUT = 30      # OVS hard timeout (s)
LINK_CAPACITY_BPS = {
    'ring': 10_000_000,     # 10 Mbps outer ring
    'hub' : 100_000_000,    # 100 Mbps hub spokes
}

# Reward weights
W_BW    =  0.5   # bandwidth   (higher = better)
W_DELAY = -0.3   # delay       (higher = worse)
W_LOSS  = -5.0   # packet loss (massive penalty)

# Logging
LOG_CSV  = 'ite_stats.csv'
LOG_COLS = ['timestamp', 'dpid', 'port', 'tx_bytes', 'rx_bytes',
            'avail_bw_mbps', 'latency_ms', 'loss_pct', 'reward']


# ─────────────────────────────────────────────────────────────────────────────
#  Helper — pretty logger
# ─────────────────────────────────────────────────────────────────────────────
logging.basicConfig(
    level   = logging.INFO,
    format  = '[%(asctime)s] %(levelname)-8s  %(message)s',
    datefmt = '%H:%M:%S',
)
LOG = logging.getLogger('ITE')


# ─────────────────────────────────────────────────────────────────────────────
#  Q-Learning Agent
# ─────────────────────────────────────────────────────────────────────────────
class QLearningAgent:
    """
    Tabular Q-Learning agent.

    State  : (source_dpid, destination_mac)   → encoded as an integer index
    Action : next-hop output port on the current switch  (1 … MAX_PORTS)

    Q-Table shape : [num_states, MAX_PORTS]
    """

    def __init__(self, num_states: int, num_actions: int):
        self.q_table  = np.zeros((num_states, num_actions), dtype=np.float32)
        self.epsilon  = EPSILON_START
        self.episode  = 0
        LOG.info('Q-Table initialised  shape=%s', self.q_table.shape)

    # ── Core update (Bellman equation) ────────────────────────────────────
    def update(self, state: int, action: int, reward: float, next_state: int):
        """
        Q(s,a) ← Q(s,a) + α · [r + γ · max Q(s',·) − Q(s,a)]
        """
        if state >= self.q_table.shape[0] or next_state >= self.q_table.shape[0]:
            return                           # guard against index overflow

        current_q  = self.q_table[state, action]
        future_max = np.max(self.q_table[next_state])
        td_target  = reward + GAMMA * future_max
        td_error   = td_target - current_q
        self.q_table[state, action] += ALPHA * td_error

    # ── Action selection (ε-greedy) ───────────────────────────────────────
    def choose_action(self, state: int, valid_ports: list) -> int:
        """
        With probability ε pick a random port (explore).
        Otherwise pick the port with the highest Q-value (exploit).
        Returns a valid port number (1-indexed).
        """
        if not valid_ports:
            return 1                         # fallback

        if random.random() < self.epsilon:
            return random.choice(valid_ports)

        if state >= self.q_table.shape[0]:
            return random.choice(valid_ports)

        # Map valid ports to action indices (0-indexed)
        port_q = {p: self.q_table[state, p - 1] for p in valid_ports}
        best   = max(port_q, key=port_q.get)
        return best

    # ── Epsilon decay (called after each monitoring round) ────────────────
    def decay_epsilon(self):
        self.episode += 1
        self.epsilon  = max(EPSILON_MIN, self.epsilon * EPSILON_DECAY)

    # ── Serialise Q-Table for inspection ─────────────────────────────────
    def save_q_table(self, path: str = 'q_table.npy'):
        np.save(path, self.q_table)
        LOG.info('Q-Table saved → %s', path)


# ─────────────────────────────────────────────────────────────────────────────
#  Reward Calculator
# ─────────────────────────────────────────────────────────────────────────────
class RewardCalculator:
    """
    Converts raw port statistics into a scalar reward signal.

    reward = W_BW  * norm(avail_bw)
           + W_DELAY * norm(latency)
           + W_LOSS  * loss_pct
    """

    def __init__(self):
        self._prev_stats: dict = {}          # (dpid, port) → (bytes, time)

    def compute(self,
                dpid       : int,
                port       : int,
                tx_bytes   : int,
                rx_bytes   : int,
                duration_s : float) -> dict:
        """
        Returns a dict with avail_bw_mbps, latency_ms, loss_pct, reward.
        """
        key       = (dpid, port)
        now       = time.time()

        # ── Bandwidth ─────────────────────────────────────────────────────
        if key in self._prev_stats:
            prev_tx, prev_rx, prev_time = self._prev_stats[key]
            dt        = max(now - prev_time, 0.001)
            tx_rate   = (tx_bytes - prev_tx) * 8 / dt          # bps
            rx_rate   = (rx_bytes - prev_rx) * 8 / dt          # bps
            used_bps  = max(tx_rate, rx_rate)
        else:
            used_bps  = 0.0

        self._prev_stats[key] = (tx_bytes, rx_bytes, now)

        cap_bps       = LINK_CAPACITY_BPS['hub'] if port >= 5 else LINK_CAPACITY_BPS['ring']
        avail_bps     = max(cap_bps - used_bps, 0.0)
        avail_bw_mbps = avail_bps / 1_000_000
        norm_bw       = avail_bps / cap_bps             # 0 … 1

        # ── Simulated latency (μs → ms)  ──────────────────────────────────
        # In a real deployment this would come from LLDP/OAM probes.
        # Here we simulate it proportionally to link utilisation.
        utilisation   = min(used_bps / cap_bps, 1.0)
        base_delay_ms = 1.0 if port >= 5 else 5.0
        latency_ms    = base_delay_ms * (1.0 + 4.0 * utilisation)  # 1–5× under load

        # ── Simulated packet loss ─────────────────────────────────────────
        # Loss spikes sharply above 90 % utilisation (tail-drop model)
        loss_pct      = max(0.0, (utilisation - 0.9) * 100.0) if utilisation > 0.9 else 0.0

        # ── Reward ────────────────────────────────────────────────────────
        reward = (W_BW    * norm_bw
                  + W_DELAY * (latency_ms / 20.0)   # normalise to ~[0,1]
                  + W_LOSS  * (loss_pct  / 100.0))

        return {
            'avail_bw_mbps': round(avail_bw_mbps, 3),
            'latency_ms'   : round(latency_ms,    3),
            'loss_pct'     : round(loss_pct,       3),
            'reward'       : round(reward,         4),
        }


# ─────────────────────────────────────────────────────────────────────────────
#  Main Ryu Application
# ─────────────────────────────────────────────────────────────────────────────
class ITE_Controller(app_manager.RyuApp):
    """
    Ryu application that binds together:
      • OpenFlow 1.3 event handling
      • Periodic port-statistics collection
      • Reward computation
      • Q-Learning agent
      • MAC learning table
      • Flow-rule installation
    """
    OFP_VERSIONS = [ofproto_v1_3.OFP_VERSION]

    # ── Init ──────────────────────────────────────────────────────────────
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # MAC learning:  {dpid: {mac: port}}
        self.mac_to_port: dict = defaultdict(dict)

        # Datapaths registered by switches:  {dpid: datapath}
        self.datapaths: dict = defaultdict(None)

        # Neighbour topology (static description of our ring-hub)
        # Each switch knows which ports lead to which neighbour dpid.
        # Port numbering is determined by the order addLink() was called
        # in topology.py — adjust if your Mininet assigns different ports.
        #
        #  s1 (dpid=1): port1→s2(ring), port2→s4(ring), port3→s5(hub), port4→h1
        #  s2 (dpid=2): port1→s1,       port2→s3,       port3→s5,      port4→h2
        #  s3 (dpid=3): port1→s2,       port2→s4,       port3→s5,      port4→h3
        #  s4 (dpid=4): port1→s3,       port2→s1,       port3→s5,      port4→h4
        #  s5 (dpid=5): port1→s1,       port2→s2,       port3→s3,      port4→s4
        self.topo: dict = {
            1: {2: 1, 4: 2, 5: 3},   # dpid 1 → {neighbour_dpid: out_port}
            2: {1: 1, 3: 2, 5: 3},
            3: {2: 1, 4: 2, 5: 3},
            4: {3: 1, 1: 2, 5: 3},
            5: {1: 1, 2: 2, 3: 3, 4: 4},
        }

        # State encoding:  (src_dpid, dst_mac_int) → int  (lazy, grows on demand)
        self._state_map: dict  = {}
        self._state_counter: int = 0
        NUM_STATES = 512        # enough headroom for our small topology

        # Instantiate sub-systems
        self.agent      = QLearningAgent(NUM_STATES, MAX_PORTS)
        self.reward_calc = RewardCalculator()

        # Per-port last reward  {(dpid, port): reward}  used as next_state proxy
        self._port_reward: dict = defaultdict(float)

        # Pandas stats log
        self._log_rows: list = []

        # Launch background monitor thread
        self.monitor_thread = hub.spawn(self._monitor_loop)

        LOG.info('═' * 60)
        LOG.info('  ITE Controller started — OpenFlow 1.3')
        LOG.info('  Q-Learning  α=%.2f  γ=%.2f  ε=%.2f', ALPHA, GAMMA, EPSILON_START)
        LOG.info('═' * 60)

    # ─────────────────────────────────────────────────────────────────────
    #  State encoding helper
    # ─────────────────────────────────────────────────────────────────────
    def _encode_state(self, src_dpid: int, dst_mac: str) -> int:
        key = (src_dpid, dst_mac)
        if key not in self._state_map:
            self._state_map[key] = self._state_counter
            self._state_counter += 1
        return self._state_map[key] % self.agent.q_table.shape[0]

    # ─────────────────────────────────────────────────────────────────────
    #  OpenFlow event: SwitchFeatures  (fires when switch connects)
    # ─────────────────────────────────────────────────────────────────────
    @set_ev_cls(ofp_event.EventOFPSwitchFeatures, CONFIG_DISPATCHER)
    def switch_features_handler(self, ev):
        datapath = ev.msg.datapath
        ofproto  = datapath.ofproto
        parser   = datapath.ofproto_parser
        dpid     = datapath.id

        self.datapaths[dpid] = datapath
        LOG.info('Switch connected  dpid=%s', hex(dpid))

        # Install table-miss rule: send unknown packets to controller
        match  = parser.OFPMatch()
        actions = [parser.OFPActionOutput(ofproto.OFPP_CONTROLLER,
                                           ofproto.OFPCML_NO_BUFFER)]
        self._add_flow(datapath, priority=0, match=match, actions=actions,
                       idle_timeout=0, hard_timeout=0)

    # ─────────────────────────────────────────────────────────────────────
    #  OpenFlow event: PacketIn  (the heart of the controller)
    # ─────────────────────────────────────────────────────────────────────
    @set_ev_cls(ofp_event.EventOFPPacketIn, MAIN_DISPATCHER)
    def packet_in_handler(self, ev):
        msg      = ev.msg
        datapath = msg.datapath
        ofproto  = datapath.ofproto
        parser   = datapath.ofproto_parser
        dpid     = datapath.id
        in_port  = msg.match['in_port']

        # ── Parse the Ethernet frame ──────────────────────────────────────
        pkt     = packet.Packet(msg.data)
        eth_pkt = pkt.get_protocol(ethernet.ethernet)
        if eth_pkt is None:
            return

        dst_mac = eth_pkt.dst
        src_mac = eth_pkt.src

        # Ignore LLDP / 802.1X internally
        if eth_pkt.ethertype == ether_types.ETH_TYPE_LLDP:
            return

        # ── MAC learning ──────────────────────────────────────────────────
        self.mac_to_port[dpid][src_mac] = in_port

        # ── Determine output port ─────────────────────────────────────────
        if dst_mac in self.mac_to_port[dpid]:
            # We already know which port leads to dst — use MAC table directly
            out_port = self.mac_to_port[dpid][dst_mac]
            decision = 'mac-table'
        else:
            # Unknown destination → ask the Q-Learning agent
            state       = self._encode_state(dpid, dst_mac)
            valid_ports = self._get_valid_ports(dpid, in_port, ofproto)
            out_port    = self.agent.choose_action(state, valid_ports)
            decision    = f'q-agent(ε={self.agent.epsilon:.2f})'

            # Immediate reward: use cached reward of the chosen port
            reward     = self._port_reward.get((dpid, out_port), 0.0)
            next_state = self._encode_state(dpid, dst_mac)   # simplified: same state
            self.agent.update(state, out_port - 1, reward, next_state)

        LOG.debug('PacketIn  dpid=%d  %s→%s  in=%d  out=%d  [%s]',
                  dpid, src_mac, dst_mac, in_port, out_port, decision)

        # ── Install a flow rule (avoid future PacketIn overhead) ──────────
        if out_port != ofproto.OFPP_FLOOD:
            match  = parser.OFPMatch(in_port=in_port, eth_dst=dst_mac, eth_src=src_mac)
            actions = [parser.OFPActionOutput(out_port)]
            self._add_flow(datapath, priority=1, match=match, actions=actions,
                           idle_timeout=FLOW_IDLE_TIMEOUT,
                           hard_timeout=FLOW_HARD_TIMEOUT)

        # ── Send the current packet out immediately ───────────────────────
        data = msg.data if msg.buffer_id == ofproto.OFP_NO_BUFFER else None
        out  = parser.OFPPacketOut(
            datapath  = datapath,
            buffer_id = msg.buffer_id,
            in_port   = in_port,
            actions   = [parser.OFPActionOutput(out_port)],
            data      = data,
        )
        datapath.send_msg(out)

    # ─────────────────────────────────────────────────────────────────────
    #  OpenFlow event: PortStatsReply  (arrives after our stats request)
    # ─────────────────────────────────────────────────────────────────────
    @set_ev_cls(ofp_event.EventOFPPortStatsReply, MAIN_DISPATCHER)
    def port_stats_reply_handler(self, ev):
        dpid = ev.msg.datapath.id
        body = ev.msg.body                 # list of OFPPortStats

        for stat in sorted(body, key=lambda s: s.port_no):
            port = stat.port_no
            if port > MAX_PORTS:           # skip internal OVS pseudo-ports
                continue

            duration_s = stat.duration_sec + stat.duration_nsec * 1e-9
            metrics    = self.reward_calc.compute(
                dpid, port,
                stat.tx_bytes, stat.rx_bytes,
                duration_s,
            )

            # Cache reward for PacketIn decisions
            self._port_reward[(dpid, port)] = metrics['reward']

            # Update Q-Table with observed reward (background update)
            state  = dpid - 1            # crude state: switch index
            action = port  - 1
            if 0 <= state < self.agent.q_table.shape[0] and \
               0 <= action < self.agent.q_table.shape[1]:
                next_state = state
                self.agent.update(state, action, metrics['reward'], next_state)

            # Log row
            row = {
                'timestamp'   : time.strftime('%Y-%m-%d %H:%M:%S'),
                'dpid'        : dpid,
                'port'        : port,
                'tx_bytes'    : stat.tx_bytes,
                'rx_bytes'    : stat.rx_bytes,
                **metrics,
            }
            self._log_rows.append(row)

            LOG.info('STATS  dpid=%-2d  port=%-2d  '
                     'bw_avail=%-7.2f Mbps  lat=%-6.2f ms  '
                     'loss=%-4.1f%%  reward=%+.4f',
                     dpid, port,
                     metrics['avail_bw_mbps'],
                     metrics['latency_ms'],
                     metrics['loss_pct'],
                     metrics['reward'])

    # ─────────────────────────────────────────────────────────────────────
    #  Background monitor loop
    # ─────────────────────────────────────────────────────────────────────
    def _monitor_loop(self):
        """
        Runs as a green thread.  Every MONITOR_PERIOD seconds:
          1. Ask every registered switch for port statistics.
          2. Decay epsilon.
          3. Flush CSV log.
          4. Save Q-Table snapshot.
        """
        LOG.info('Monitor loop started  (period=%ds)', MONITOR_PERIOD)
        while True:
            for dpid, datapath in list(self.datapaths.items()):
                if datapath is None:
                    continue
                self._request_port_stats(datapath)

            self.agent.decay_epsilon()
            self._flush_csv()
            self.agent.save_q_table()

            hub.sleep(MONITOR_PERIOD)

    def _request_port_stats(self, datapath):
        """Send an OFP Port Stats Request to a switch."""
        parser  = datapath.ofproto_parser
        ofproto = datapath.ofproto
        req     = parser.OFPPortStatsRequest(datapath, 0, ofproto.OFPP_ANY)
        datapath.send_msg(req)

    # ─────────────────────────────────────────────────────────────────────
    #  CSV flush
    # ─────────────────────────────────────────────────────────────────────
    def _flush_csv(self):
        """Append buffered rows to the CSV log file."""
        if not self._log_rows:
            return
        df = pd.DataFrame(self._log_rows, columns=LOG_COLS)
        header = not os.path.exists(LOG_CSV)
        df.to_csv(LOG_CSV, mode='a', header=header, index=False)
        self._log_rows.clear()
        LOG.debug('CSV flushed → %s', LOG_CSV)

    # ─────────────────────────────────────────────────────────────────────
    #  Utility: install a flow rule
    # ─────────────────────────────────────────────────────────────────────
    def _add_flow(self, datapath, priority, match, actions,
                  idle_timeout=0, hard_timeout=0):
        ofproto = datapath.ofproto
        parser  = datapath.ofproto_parser
        inst    = [parser.OFPInstructionActions(
                       ofproto.OFPIT_APPLY_ACTIONS, actions)]
        mod     = parser.OFPFlowMod(
            datapath     = datapath,
            priority     = priority,
            match        = match,
            instructions = inst,
            idle_timeout = idle_timeout,
            hard_timeout = hard_timeout,
        )
        datapath.send_msg(mod)

 # ─────────────────────────────────────────────────────────────────────
    #  Utility: valid output ports for a switch (exclude in_port & flood)
    # ─────────────────────────────────────────────────────────────────────
    def _get_valid_ports(self, dpid: int, in_port: int, ofproto) -> list:
        """
        Return ports that are physically wired in the topology,
        excluding the port the packet arrived on.
        """
        if dpid in self.topo:
            # All ports connected to other switches
            neighbour_ports = list(self.topo[dpid].values())
            all_ports = list(neighbour_ports)

            # Add host port for edge switches (s1-s4), but leave s5 as a pure hub
            if dpid != 5:
                host_port = max(neighbour_ports) + 1
                all_ports.append(host_port)
        else:
            all_ports = list(range(1, MAX_PORTS + 1))

        valid = [p for p in all_ports if p != in_port]
        return valid if valid else [ofproto.OFPP_FLOOD]