# -*- coding: utf-8 -*-
"""Topology.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EBJNW-0xkH0qVC1oK-L8bhKb8JbCwbW1
"""

#!/usr/bin/env python3
r"""
topology.py — Mininet Network Topology
======================================
Project : Intelligent Traffic Engineering System (ITE)
Author  : SDN Lab
Python  : 3.9  |  Mininet 2.3+  |  Open vSwitch

Topology: Ring with a Central Hub
----------------------------------
                    s5 (Hub)
                   / | \
                  /  |  \
                s1  s3   (fast 100Mbps links to hub)
               /  \   \
             h1    s2   s4
                  / \     \
                h2   h3    h4

Exact layout:
  Outer Ring  : s1 — s2 — s3 — s4 — s1   (10 Mbps, 5ms delay)
  Hub Links   : s1 — s5, s2 — s5, s3 — s5, s4 — s5  (100 Mbps, 1ms delay)
  Hosts       : h1@s1, h2@s2, h3@s3, h4@s4

Run (as root / sudo):
    sudo python3 topology.py
"""

from mininet.net    import Mininet
from mininet.node   import Controller, RemoteController, OVSKernelSwitch
from mininet.cli    import CLI
from mininet.log    import setLogLevel, info
from mininet.link   import TCLink


# ─────────────────────────────────────────────
#  Link profiles
# ─────────────────────────────────────────────
RING_LINK = dict(bw=10,  delay='5ms',  loss=0, max_queue_size=100)   # slow outer ring
HUB_LINK  = dict(bw=100, delay='1ms',  loss=0, max_queue_size=1000)  # fast hub spokes
HOST_LINK = dict(bw=100, delay='0ms',  loss=0, max_queue_size=1000)  # host attachments

# Ryu controller address  (must match where you run ite.py)
RYU_IP   = '127.0.0.1'
RYU_PORT = 6633


def build_topology():
    """
    Build and start the ITE ring-hub topology.
    Blocks on the Mininet CLI until the user types 'exit'.
    """
    setLogLevel('info')

    # ── 1. Create the network ──────────────────────────────────────────────
    net = Mininet(
        controller=RemoteController,
        switch=OVSKernelSwitch,
        link=TCLink,
        autoSetMacs=True,       # deterministic MAC addresses
        autoStaticArp=False,    # let the controller handle ARP
    )

    # ── 2. Remote Ryu controller ───────────────────────────────────────────
    info('*** Adding Ryu remote controller\n')
    c0 = net.addController(
        'c0',
        controller=RemoteController,
        ip=RYU_IP,
        port=RYU_PORT,
    )

    # ── 3. Switches ────────────────────────────────────────────────────────
    info('*** Adding switches\n')
    switches = {}
    for i in range(1, 6):          # s1 … s5
        dpid = f'{i:016x}'         # zero-padded 64-bit datapath ID
        switches[f's{i}'] = net.addSwitch(
            f's{i}',
            cls=OVSKernelSwitch,
            protocols='OpenFlow13',
            dpid=dpid,
        )

    s1, s2, s3, s4, s5 = (switches[f's{i}'] for i in range(1, 6))

    # ── 4. Hosts ───────────────────────────────────────────────────────────
    info('*** Adding hosts\n')
    h1 = net.addHost('h1', ip='10.0.0.1/24', mac='00:00:00:00:00:01')
    h2 = net.addHost('h2', ip='10.0.0.2/24', mac='00:00:00:00:00:02')
    h3 = net.addHost('h3', ip='10.0.0.3/24', mac='00:00:00:00:00:03')
    h4 = net.addHost('h4', ip='10.0.0.4/24', mac='00:00:00:00:00:04')

    # ── 5. Links ───────────────────────────────────────────────────────────
    info('*** Wiring the topology\n')

    # Outer ring (slow) — s1–s2–s3–s4–s1
    net.addLink(s1, s2, **RING_LINK)
    net.addLink(s2, s3, **RING_LINK)
    net.addLink(s3, s4, **RING_LINK)
    net.addLink(s4, s1, **RING_LINK)

    # Hub spokes (fast) — each switch → s5
    net.addLink(s1, s5, **HUB_LINK)
    net.addLink(s2, s5, **HUB_LINK)
    net.addLink(s3, s5, **HUB_LINK)
    net.addLink(s4, s5, **HUB_LINK)

    # Host attachments
    net.addLink(h1, s1, **HOST_LINK)
    net.addLink(h2, s2, **HOST_LINK)
    net.addLink(h3, s3, **HOST_LINK)
    net.addLink(h4, s4, **HOST_LINK)

    # ── 6. Start ───────────────────────────────────────────────────────────
    info('*** Starting network\n')
    net.build()
    c0.start()
    for sw in switches.values():
        sw.start([c0])

    # ── 7. Print topology summary ──────────────────────────────────────────
    info('\n')
    info('╔══════════════════════════════════════════════════════╗\n')
    info('║      ITE Ring-Hub Topology — Ready                   ║\n')
    info('╠══════════════════════════════════════════════════════╣\n')
    info('║  Outer ring  : s1─s2─s3─s4─s1  @  10 Mbps / 5 ms     ║\n')
    info('║  Hub spokes  : s1,s2,s3,s4 ─► s5  @ 100 Mbps / 1ms   ║\n')
    info('║  Hosts       : h1@s1  h2@s2  h3@s3  h4@s4            ║\n')
    info('║  Controller  : Ryu @ 127.0.0.1:6633  (OpenFlow 1.3)  ║\n')
    info('╚══════════════════════════════════════════════════════╝\n')
    info('\n')

    # ── 8. Quick connectivity test ─────────────────────────────────────────
    info('*** Running pingAll to verify connectivity\n')
    net.pingAll()

    # ── 9. Hand off to interactive CLI ────────────────────────────────────
    info('*** Entering Mininet CLI  (type "exit" to stop)\n')
    CLI(net)

    # ── 10. Teardown ───────────────────────────────────────────────────────
    info('*** Stopping network\n')
    net.stop()


if __name__ == '__main__':
    build_topology()